add skip-tests in full-tests

diff --git a/.github/workflows/full_tests.yml b/.github/workflows/full_tests.yml
--- a/.github/workflows/full_tests.yml
+++ b/.github/workflows/full_tests.yml
@@ -7,13 +7,51 @@ on:
     types: [ submitted ]
 
 jobs:
-  lint-unittests-docs-build:
-    name: Lint, Unit tests, Docs and Build
+  check-previous-checks:
+    name: Check previous checks
     runs-on: ubuntu-latest
     if: >-
       github.event.review.state == 'approved'
       || github.event.review.body == 'recheck-snap'
       || github.event.review.body == 'recheck-full'
+    outputs:
+      skip: ${{ steps.skip-tests.outputs.skip }}
+    steps:
+      - uses: actions/checkout@v2
+        with:
+          fetch-depth: 3
+      - name: Get latest workflow run status
+        uses: actions/github-script@v4
+        id: latest-workflow
+        with:
+          script: |
+            const runs = await github.actions.listWorkflowRuns({
+              owner: context.repo.owner,
+              repo: context.repo.repo,
+              workflow_id: 'tests.yml',
+              per_page: 2
+            })
+            return runs.data.workflow_runs[1]
+      - name: Track changed files since lastest workflow
+        id: latest-workflow-code-changed
+        env:
+          LATEST_HEAD_SHA: ${{ fromJson(steps.latest-workflow.outputs.result).head_sha }}
+        run: |
+          failed=1
+          git diff --name-only $LATEST_HEAD_SHA | grep -qE '^(./juju_verify|./tests)' || failed=0
+          echo "::set-output name=changed::$failed"
+      - name: Skip tests
+        id: skip-tests
+        if: >-
+          fromJson(steps.latest-workflow.outputs.result).conclusion == "success"
+          && steps.latest-workflow-code-changed.outputs.changed == 0
+        run: echo "::set-output name=skip::1"
+
+  lint-unittests-docs-build:
+    name: Lint, Unit tests, Docs and Build
+    runs-on: ubuntu-latest
+    needs: check-previous-checks
+    if: needs.check-previous-checks.outputs.skip
     strategy:
       fail-fast: true
       matrix:
@@ -43,10 +81,6 @@ jobs:
     name: Build snap
     runs-on: ubuntu-latest
     needs: lint-unittests-docs-build
-    if: >-
-      github.event.review.state == 'approved'
-      || github.event.review.body == 'recheck-snap'
-      || github.event.review.body == 'recheck-full'
     outputs:
       code-changed: ${{ steps.code-changed.outputs.changed }}
     steps:
@@ -60,8 +94,8 @@ jobs:
       run: |
         git remote add upstream https://github.com/canonical/juju-verify
         git fetch upstream master
-        failed=0
-        git diff --name-only upstream/master | grep -qE '^(juju_verify|tests)' || failed=1
+        failed=1
+        git diff --name-only upstream/master | grep -qE '^(./juju_verify|./tests)' || failed=0
         echo "::set-output name=changed::$failed"
 
   func-tests:
@@ -69,10 +103,7 @@ jobs:
     runs-on: self-hosted
     needs: build-snap
     if: >-
-      (
-        github.event.review.state == 'approved'
-        && needs.build-snap.outputs.code-changed == 0
-      )
+      needs.build-snap.outputs.code-changed == 1
       || github.event.review.body == 'recheck-full'
     steps:
       - uses: actions/checkout@v2
