[WIP] update GitHub tests workflow
 - [comment] add "recheck-snap" trigger
 - [comment] add "recheck-full" trigger
 - [review] add "APPROVED" trigger
 - TODO: check if test need to run again

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -4,12 +4,25 @@ name: Test suite
 
 on:
   pull_request:
+    types: [ opened, synchronize, reopened, ready_for_review ]
     branches: [ master ]
 
+  issue_comment:
+    types: [ created ]
+
 jobs:
-  lint-unittests-docs:
-    name: Lint, Unit tests and Docs
+  lint-unittests-docs-build:
+    name: Lint, Unit tests, Docs and Build
     runs-on: ubuntu-latest
+    if: >-
+      github.event_name == 'pull_request'
+      || (
+        github.event_name == 'issue_comment'
+        && (
+          github.event.issue_comment.comment.body == 'recheck-snap'
+          || github.event.issue_comment.comment.body == 'recheck-full'
+        )
+      )
     strategy:
       fail-fast: true
       matrix:
@@ -38,18 +51,52 @@ jobs:
   build-snap:
     name: Build snap
     runs-on: ubuntu-latest
-    needs: lint-unittests-docs
+    needs: lint-unittests-docs-build
+    if: >-
+      (
+        github.event_name == 'pull_request'
+        && !github.event.pull_request.draft
+        && github.event.pull_request_review.state == 'APPROVED'
+      )
+      || (
+        github.event_name == 'issue_comment'
+        && (
+          github.event.issue_comment.comment.body == 'recheck-snap'
+          || github.event.issue_comment.comment.body == 'recheck-full'
+        )
+      )
+    outputs:
+      code-changed: ${{ steps.code-changed.outputs.changed }}
     steps:
     - uses: actions/checkout@v2
     - uses: snapcore/action-build@v1
       id: snapcraft
     - name: Install snap
       run: sudo snap install --dangerous ${{ steps.snapcraft.outputs.snap }}
+    - name: Track changed files in the PR
+      id: code-changed
+      run: |
+        git remote add upstream https://github.com/canonical/juju-verify
+        git fetch upstream master
+        failed=0
+        git diff --name-only upstream/master | grep -qE '^(juju_verify|tests)' || failed=1
+        echo "::set-output name=changed::$failed"
 
   func-tests:
     name: Integration tests
     runs-on: self-hosted
     needs: build-snap
+    if: >-
+      (
+        github.event_name == 'pull_request'
+        && !github.event.pull_request.draft
+        && github.event.pull_request_review.state == 'APPROVED'
+        && needs.build-snap.outputs.code-changed == 0
+      )
+      || (
+        github.event_name == 'issue_comment'
+        && github.event.issue_comment.comment.body == 'recheck-full'
+      )
     steps:
       - uses: actions/checkout@v2
       - name: Set up Python 3.8
